name: Run Unit Test

on:
  push:
    branches: [ US1 ]
  pull_request:
    branches: [ US1 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'


      - name: Run Unit Test for Answered Toggle Button
        run: npx mocha test/answer-toggle-test.js
